### PR TITLE
Fix field with boolean option, e.g. [deprecation = true]

### PR DESCRIPTION
**Pull request by millin**

### CODE REVIEW

**Comment by criccomini** [comment]
Looks like there's some style related issues. PTAL.

**Comment by criccomini** [comment]
Published to:

https://pypi.org/project/proto-schema-parser/1.4.3/

**Comment by millin** [comment]
@criccomini Hi!
Why did you remove the changes to generator? Now it writes the option as `[deprecation = “true”]`.

**Comment by criccomini** [comment]
I was under the impression that you made that change to placate the Python type hinting linter.I've updated the code in this PR re-add it: https://github.com/criccomini/proto-schema-parser/pull/44.

A test would have prevented this confusion. I have added one.

I have published 1.4.4 with #44 merged.

**Pull request merged**
